# -*- coding: utf-8 -*-
"""Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SPEyPrkRQwfGsqLmnwblXriTmtuPbohw
"""

# TAKING 2 NUMBERS AS INPUT FROM USERS
num1=float(input('Enter first number'))
num2=float(input('Enter second number'))
# TAKING OPERATOR AS INPUT FROM USER
operator=input('Enter an operator')
# BASED ON OPERATOR CHOICE MADE BY USER PERFORMING ARITHMETIC OPERATIONS
if operator=='+':
  print('addition:',num1+num2)
elif operator=='-':
  print('subtraction:',num1-num2)
elif operator=='*':
  print('multiplication:',num1*num2)
elif operator=='/':
  if num2!=0:
    print('divide:',num1/num2)
  else:
    print('cant divide by 0')
else:
  print('cant divide by 0')
